### ISSUE TITLE
Try `browser-pack-flat` & `common-shakeify`

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly-webpack#2]
(@rreusser posting here thinking you might know these plugins already.)

I came across [`browser-pack-flat`](https://github.com/goto-bus-stop/browser-pack-flat) and [`common-shakeify`](https://github.com/goto-bus-stop/common-shakeify) yesterday. Together they bring the _best_ of [rollup](https://github.com/rollup/rollup#tree-shaking) to browserify. 

It might be interesting to see if they can shave off some bytes from our bundles :burrito: :hamburger:

**Comment by rreusser** [comment]
Nice! I'll try. Yeah. Started working through the browserify org to learn some new things but these seem definitely worth a try.

**Comment by bpostlethwaite** [comment]
This may be the plan already but it may be useful to put advanced "production" configurations in their own folders. That way there is a _super_ simple example to illustrate the basics.

**Comment by rreusser** [comment]
TBH I'm not 100% sure the plan for this repo. In some sense maybe the goal is for it to disappear entirely and be absorbed into the plotly docs. In which case this is all a bit moot beyond a working example for testing and turning this into paragraph form.

**Comment by rreusser** [comment]
Okay, finally tested the flags. For the kitchen sink build:

| bundle size     | uglify | uglifyify | envify | compress_attributes | bundle-collapser | common-shakeify | browser-pack-flat |
|-----------------|--------|-----------|--------|---------------------|------------------|-----------------|-------------------|
| 5903436 (5.6 M) |        |           |        |                     |                  |                 |                   |
| 2422679 (2.3M)  |    ✔︎   |           |        |                     |                  |                 |                   |
| 2465302 (2.4M)  |    ✔︎   |     ✔︎     |        |                     |                  |                 |                   |
| 2422679 (2.3M)  | ✔︎      |           | ✔︎      |                     |                  |                 |                   |
| 2280292 (2.2M)  | ✔︎      |           | ✔︎      | ✔︎                   |                  |                 |                   |
| 2189962 (2.1M)  | ✔︎      |           | ✔︎      | ✔︎                   | ✔︎                |                 |                   |
| 2189962 (2.1M)  | ✔︎      |           | ✔︎      | ✔︎                   | ✔︎                | ✔︎               |                   |
| <strike>2133044 (2.0M)</strike> | ✔︎      |           | ✔︎      | ✔︎                   | ✔︎                | ✔︎               | ✔︎                 |

So nothing too dramatic, but steadily chips away at those bytes. Except for uglifyify. Which adds a few bytes. And browser-pack-flat, which I am somewhat confident is failing due to the extra function wrapping required to accommodate circular dependencies.
